apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'maven-publish'

ext.abiCodes = ["armeabi-v7a": 1, "arm64-v8a": 2, "x86":3, "x86_64":4]
ext.universalBase = 8000

version = "0.1.1"

android {
    namespace 'is.xyz.mpv'
    compileSdk 34

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 34

        versionCode 38
        versionName version
    }

    buildFeatures {
        buildConfig = true
    }

    // https://youtrack.jetbrains.com/issue/KT-55947
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile) {
        kotlinOptions.jvmTarget = JavaVersion.VERSION_11.toString()
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
}

def getVersionName = { ->
    return version
}

def getGroupId = { ->
    return "com.github.shovelkun"
}

task sourceJar(type: Jar) {
    archiveClassifier = 'sources'
    from android.sourceSets.main.java.srcDirs
}

publishing {
    publications {
        bar(MavenPublication) {
            groupId getGroupId()
            version getVersionName()
            // Place the path of your artifact here
            artifact("${buildDir}/outputs/aar/mpv-android-lib-v${version}.aar")
            artifact(tasks["sourceJar"])
        }
    }
}
